### ISSUE TITLE
Examples not working

### ISSUE THREAD

**Issue by AlexanderMath** [fishjojo/pyscfad#15]
Tried

1 https://github.com/fishjojo/pyscfad/blob/main/examples/scf/00-simple.py gives 
```
ad/lib/python3.8/site-packages/pyscf/scf/diis.py", line 85, in get_err_vec_orig
    raise RuntimeError('Unknown SCF DIIS type')
```

2 https://github.com/fishjojo/pyscfad/blob/main/examples/scf/01-hessian.py

```
AttributeError: /nethome/alexm/miniconda3/envs/ad/lib/python3.8/site-packages/pyscf/lib/libcgto.so: undefined symbol: int1e_kin_dr10_optimizer
```

3 https://github.com/fishjojo/pyscfad/blob/main/examples/dft/00-simple.py
```
  File "/nethome/alexm/miniconda3/envs/ad/lib/python3.8/site-packages/pyscf/scf/hf.py", line 946, in get_fock
    f = h1e + vhf
TypeError: unsupported operand type(s) for +: 'float' and 'VXC'
```

I was able to fix 1 and 3, but not sure how to fix 2. Perhaps if I rebuild libcint from scratch?

**Comment by fishjojo** [comment]
Please use the pyscfad dev branch for now. The main branch is broken.
Also please compile the pyscf from source in this branch https://github.com/fishjojo/pyscf/tree/ad.
I plan to make pyscfad a standalone package, and will do an upgrade later.
