### ISSUE TITLE
Different errors running examples

### ISSUE THREAD

**Issue by pietrodalcin00** [fishjojo/pyscfad#17]
I tried installing the development version of pyscfad via `pip install git+https://github.com/fishjojo/pyscfad.git` in a conda environment on an arm64 M1 Mac. All the dependencies seem to be automatically installed (h5py, scipy, pyscf, pyscfproperties, jax etc..), and the installation runs smoothly. Trying to run any of the scf examples (after creating the .pyscf_conf.py file with the required configuration), I get the following error at the mf.kernel() (pasting the last instance of the erorr only):

```
...

File ~/anaconda3/envs/PyAD/lib/python3.11/site-packages/pyscf/lib/linalg_helper.py:1509, in cho_solve(a, b, strict_sym_pos)
   1502 '''Solve ax = b, where a is a positive definite hermitian matrix
   1503 
   1504 Kwargs:
   1505     strict_sym_pos (bool) : Whether to impose the strict positive definition
   1506         on matrix a
   1507 '''
   1508 try:
-> 1509     return scipy.linalg.solve(a, b, sym_pos=True)
   1510 except numpy.linalg.LinAlgError:
   1511     if strict_sym_pos:

TypeError: solve() got an unexpected keyword argument 'sym_pos'

```

Other type of examples give different errors, for example libraries not loaded for dft examples.
If I instead install by specifying the developer branch via "pip install git+https://github.com/fishjojo/pyscfad.git@dev" I get an error at `from pyscfad import gto, scf` leading to:

`libao2mo_vjp = load_library('libao2mo_vjp'), OSError: no file with expected extension`

Please let me know if I'm doing something wrong in the installation process, and if so what sequence of commands would be best to get the right installation. Thank you

**Comment by fishjojo** [comment]
Please use scipy<1.11, and the pyscf here https://github.com/fishjojo/pyscf/tree/ad.
For the dev branch of pyscfad, you will need to compile the code in pyscfadlib (just `cmake` then `make`).
In the next release, pyscfad will work with the latest pyscf.

**Comment by fishjojo** [comment]
You can try the combination of `pip install pyscfad` and `pip install git+https://github.com/fishjojo/pyscf.git@ad` and see if it works.
The error above seems to be that the BLAS library is not properly linked.

**Comment by pietrodalcin00** [comment]
Hi, I tried to just pip install pyscfad but the usual `solve() got an unexpected keyword argument 'sym_pos'` error shows up in the examples. Do you have any tips on how to solve the linking problem for the compiling error? I tried to install llvm and ibomp with brew but the compiler seems to look for libraries (I get tons of warning regarding this) in the /usr/local directory which is the old intel location of homebrew installations. Could the problem be the arm64 architecture of my M1 Mac?

**Comment by fishjojo** [comment]
For the error of `sym_pos`, you need to downgrade `scipy` to versions < 1.11.

For the compiling issue, unfortunately, I don't have any suggestions.

**Comment by pietrodalcin00** [comment]
I downgraded scipy and a new error shows up, seemingly related to the pyscf installation

File ~/anaconda3/envs/pyad/lib/python3.11/site-packages/pyscf/pyscf/scf/diis.py:85, in get_err_vec_orig(s, d, f)
     81     errvec = numpy.hstack([
     82         get_err_vec_orig(s, d[0], f[0]).ravel(),
     83         get_err_vec_orig(s, d[1], f[1]).ravel()])
     84 else:
---> 85     raise RuntimeError('Unknown SCF DIIS type')
     86 return errvec

RuntimeError: Unknown SCF DIIS type

Any suggestions?

**Comment by fishjojo** [comment]
Please try this commit 
`pip install git+https://github.com/fishjojo/pyscf.git@4c3dcfb1226690a9013a0bdaffe08ef9113a3c77`
I should update the installation procedure.

**Comment by pietrodalcin00** [comment]
Hi,

I now finally managed to install everything. Thanks a lot. However, while the example in `scf/00-simple.py` works, the one in `scf/10-polarizability.py` doesn't (and I'd like to compute polarizabilities). Any hints as to why the example fails?

```
Traceback (most recent call last):
  File "/Users/fraringhieri/Desktop/DTU/QC/10-polarizability.py", line 23, in <module>
    polar = jax.jacfwd(apply_E)(E0)
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fraringhieri/anaconda3/envs/pyad/lib/python3.11/site-packages/jax/_src/api.py", line 860, in jacfun
    y, jac = vmap(pushfwd, out_axes=(None, -1))(_std_basis(dyn_args))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/fraringhieri/Desktop/DTU/QC/10-polarizability.py", line 19, in apply_E
    mf.kernel()
  File "/Users/fraringhieri/anaconda3/envs/pyad/lib/python3.11/site-packages/pyscfad/scf/hf.py", line 292, in kernel
    kernel(self, self.conv_tol, self.conv_tol_grad,
  File "/Users/fraringhieri/anaconda3/envs/pyad/lib/python3.11/site-packages/pyscfad/scf/hf.py", line 165, in kernel
    _scf(mo_coeff, mf, s1e, h1e, mo_occ, dm0=dm,
  File "/Users/fraringhieri/anaconda3/envs/pyad/lib/python3.11/site-packages/pyscfad/_src/implicit_diff.py", line 87, in wrapped_solver_fun
    return make_custom_vjp_solver_fun(solver_fun, ba.kwargs)(*ba.args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: can't apply forward-mode autodiff (jvp) to a custom_vjp function.
```

**Comment by fishjojo** [comment]
If you set `pyscfad_scf_implicit_diff=True` in the PySCF configure file ($HOME/.pyscf_conf.py), then it will only works with reverse mode differentiation.
In this example, forward mode differentiation is used (i.e., `jax.jacfwd`). In order to make it work, please turn off the implicit differentiation for SCF by setting `pyscfad_scf_implicit_diff=False`.
Or you could use reverse mode differentiation by replacing `jacfwd` in the example with `jacrev`. But `hessian` won't work, since  it is computed by `jacfwd(jacrev(func))`.
