### ISSUE TITLE
RDM implementation

### ISSUE THREAD

**Issue by pietrodalcin00** [fishjojo/pyscfad#19]
I was looking through the code to see how to call a make_rdm1 function for FCI wave functions, but I can't seem to find one. Is it yet to be implemented? Are there any plans? I have been computing polarizabilities at different levels and it seems to me that having to call jacrev only once on the dipole object would yield less computing time than doing an hessian computation. These two options are available in your scf polarizability example, but without the rdm1 I can't get the FCI dipole.

**Comment by fishjojo** [comment]
FCI density matrix is not implemented. You may try this code https://github.com/pyscf/pyscf/blob/290126a7829d7fe51309ce061782d6ea31ca0797/pyscf/fci/fci_slow.py#L185-L196
and replace `numpy` with `jax.numpy`.
Note that the current FCI implementation in pyscfad is very slow, but I don't have time to improve it in the near term.
