### ISSUE TITLE
pyscf install issue

### ISSUE THREAD

**Issue by zhouyz08** [fishjojo/pyscfad#4]
Hi I am interested in the auto diff features but the following problem came to me when installing...

Basically when I tried to pip install the pyscf @ git+https://github.com/fishjojo/pyscf.git@ad#egg=pyscf, it throws errors:
'''error: subprocess-exited-with-error
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [10 lines of output]
      /mnt/c/MyProgram/anaconda3/envs/pyscfad/lib/python3.9/site-packages/setuptools/dist.py:516: UserWarning: Normalizing '2.0.0a' to '2.0.0a0'    
        warnings.warn(tmpl.format(**locals()))
      running bdist_wheel
      running build
      running build_ext
      Configuring extensions
      cmake -S/tmp/pip-install-cxvbs6j8/pyscf_5a7c4339a50b4cc8a4175d5e1ef23a9d/pyscf/lib -Bbuild/temp.linux-x86_64-3.9
      CMake Error: The source directory "" does not exist.
      Specify --help for usage, or press the help button on the CMake GUI.
      error: command '/usr/bin/cmake' failed with exit code 1
      [end of output]'''

I also tried with the original pyscf from pip install, and manually installed the pyscfad. This error came to me when importing pyscfad:
'''ImportError                               Traceback (most recent call last)
Input In [6], in <cell line: 1>()
----> 1 from pyscfad import gto

File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/__init__.py:1, in <module>
----> 1 from pyscfad.gto import mole
      2 from pyscfad.gto.mole import Mole

File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/mole.py:8, in <module>
      6 from pyscf.gto.mole import PTR_ENV_START
      7 from pyscfad import util
----> 8 from pyscfad.lib import ops, custom_jvp
      9 from pyscfad.gto import moleintor
     10 from pyscfad.gto.eval_gto import eval_gto

File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/lib/__init__.py:1, in <module>
----> 1 from pyscf.lib import ops
      2 #from pyscfad.lib import ops
      3 #from pyscfad.lib.ops import *
      4 from pyscfad.lib import jax_helper

ImportError: cannot import name 'ops' from 'pyscf.lib' (/mnt/c/MyProgram/anaconda3/envs/pyscfad/lib/python3.9/site-packages/pyscf/lib/__init__.py)'''

I have the experience to use pyscf before and it worked well... Is there anything I messed up in the installation?
Any suggestions would be appreciated!

Yuzhi

**Comment by zhouyz08** [comment]
An update:
I tried install manually both the pyscf (from your branch) and pyscfad. The compiling process looks okay. But when I tried 'from pyscfad import gto', it throws the errors like following:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [14], in <cell line: 3>()
      1 import jax
      2 import numpy
----> 3 from pyscfad import gto

File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/__init__.py:1, in <module>
----> 1 from pyscfad.gto import mole
      2 from pyscfad.gto.mole import Mole

File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/mole.py:4, in <module>
      2 from pyscf import __config__
      3 from pyscf import numpy as np
----> 4 from pyscf import gto
      5 from pyscf.lib import logger, param
      6 from pyscf.gto.mole import PTR_ENV_START

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/gto/__init__.py:19, in <module>
      1 #!/usr/bin/env python
      2 # Copyright 2014-2018 The PySCF Developers. All Rights Reserved.
      3 #
   (...)
     16 # Author: Qiming Sun <osirpt.sun@gmail.com>
     17 #
---> 19 from pyscf.gto import mole
     20 from pyscf.gto import basis
     21 from pyscf.gto.basis import parse, load, parse_ecp, load_ecp

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/gto/mole.py:40, in <module>
     38 import contextlib
     39 import threading
---> 40 from pyscf import lib
     41 from pyscf.lib import param
     42 from pyscf.data import elements

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/lib/__init__.py:24, in <module>
     22 from pyscf.lib import parameters
     23 param = parameters
---> 24 from pyscf.lib import numpy_helper
     25 from pyscf.lib import linalg_helper
     26 from pyscf.lib import scipy_helper

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/lib/numpy_helper.py:40, in <module>
     37 except (ImportError, OSError):
     38     FOUND_TBLIS = False
---> 40 _np_helper = misc.load_library('libnp_helper')
     42 BLOCK_DIM = 192
     43 PLAIN = 0

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/lib/misc.py:54, in load_library(libname)
     52 try:
     53     _loaderpath = os.path.dirname(__file__)
---> 54     return numpy.ctypeslib.load_library(libname, _loaderpath)
     55 except OSError:
     56     from pyscf import __path__ as ext_modules

File /mnt/c/MyProgram/anaconda3/envs/pyscfad/lib/python3.9/site-packages/numpy/ctypeslib.py:163, in load_library(libname, loader_path)
    161             raise
    162 ## if no successful return in the libname_ext loop:
--> 163 raise OSError("no file with expected extension")

OSError: no file with expected extension
--------------------------------------------------------------------------------------------------------
Also, I have included the lines:
pyscfad = True
pyscf_numpy_backend = 'jax'
pyscf_scipy_linalg_backend = 'pyscfad'
pyscf_scipy_backend = 'jax'
pyscfad_scf_implicit_diff = True      
pyscfad_ccsd_implicit_diff = True     
in the .pyscf_conf.py both in the home and working directories...

Thanks for helping me,

Yuzhi


> Hi I am interested in the auto diff features but the following problem came to me when installing...
> 
> Basically when I tried to pip install the pyscf @ git+https://github.com/fishjojo/pyscf.git@ad#egg=pyscf, it throws errors: '''error: subprocess-exited-with-error × python setup.py bdist_wheel did not run successfully. │ exit code: 1 ╰─> [10 lines of output] /mnt/c/MyProgram/anaconda3/envs/pyscfad/lib/python3.9/site-packages/setuptools/dist.py:516: UserWarning: Normalizing '2.0.0a' to '2.0.0a0' warnings.warn(tmpl.format(**locals())) running bdist_wheel running build running build_ext Configuring extensions cmake -S/tmp/pip-install-cxvbs6j8/pyscf_5a7c4339a50b4cc8a4175d5e1ef23a9d/pyscf/lib -Bbuild/temp.linux-x86_64-3.9 CMake Error: The source directory "" does not exist. Specify --help for usage, or press the help button on the CMake GUI. error: command '/usr/bin/cmake' failed with exit code 1 [end of output]'''
> 
> I also tried with the original pyscf from pip install, and manually installed the pyscfad. This error came to me when importing pyscfad: '''ImportError Traceback (most recent call last) Input In [6], in <cell line: 1>() ----> 1 from pyscfad import gto
> 
> File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/**init**.py:1, in ----> 1 from pyscfad.gto import mole 2 from pyscfad.gto.mole import Mole
> 
> File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/mole.py:8, in 6 from pyscf.gto.mole import PTR_ENV_START 7 from pyscfad import util ----> 8 from pyscfad.lib import ops, custom_jvp 9 from pyscfad.gto import moleintor 10 from pyscfad.gto.eval_gto import eval_gto
> 
> File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/lib/**init**.py:1, in ----> 1 from pyscf.lib import ops 2 #from pyscfad.lib import ops 3 #from pyscfad.lib.ops import * 4 from pyscfad.lib import jax_helper
> 
> ImportError: cannot import name 'ops' from 'pyscf.lib' (/mnt/c/MyProgram/anaconda3/envs/pyscfad/lib/python3.9/site-packages/pyscf/lib/**init**.py)'''
> 
> I have the experience to use pyscf before and it worked well... Is there anything I messed up in the installation? Any suggestions would be appreciated!
> 
> Yuzhi

**Comment by zhouyz08** [comment]
An update:
I tried install manually both the pyscf (from your branch) and pyscfad. The compiling process looks okay. But when I tried 'from pyscfad import gto', it throws the errors like following:
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
Input In [14], in <cell line: 3>()
      1 import jax
      2 import numpy
----> 3 from pyscfad import gto

File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/__init__.py:1, in <module>
----> 1 from pyscfad.gto import mole
      2 from pyscfad.gto.mole import Mole

File /mnt/c/jsw/src/autodiff/pyscfad/pyscfad/gto/mole.py:4, in <module>
      2 from pyscf import __config__
      3 from pyscf import numpy as np
----> 4 from pyscf import gto
      5 from pyscf.lib import logger, param
      6 from pyscf.gto.mole import PTR_ENV_START

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/gto/__init__.py:19, in <module>
      1 #!/usr/bin/env python
      2 # Copyright 2014-2018 The PySCF Developers. All Rights Reserved.
      3 #
   (...)
     16 # Author: Qiming Sun <osirpt.sun@gmail.com>
     17 #
---> 19 from pyscf.gto import mole
     20 from pyscf.gto import basis
     21 from pyscf.gto.basis import parse, load, parse_ecp, load_ecp

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/gto/mole.py:40, in <module>
     38 import contextlib
     39 import threading
---> 40 from pyscf import lib
     41 from pyscf.lib import param
     42 from pyscf.data import elements

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/lib/__init__.py:24, in <module>
     22 from pyscf.lib import parameters
     23 param = parameters
---> 24 from pyscf.lib import numpy_helper
     25 from pyscf.lib import linalg_helper
     26 from pyscf.lib import scipy_helper

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/lib/numpy_helper.py:40, in <module>
     37 except (ImportError, OSError):
     38     FOUND_TBLIS = False
---> 40 _np_helper = misc.load_library('libnp_helper')
     42 BLOCK_DIM = 192
     43 PLAIN = 0

File /mnt/c/jsw/src/autodiff/pyscf/pyscf/lib/misc.py:54, in load_library(libname)
     52 try:
     53     _loaderpath = os.path.dirname(__file__)
---> 54     return numpy.ctypeslib.load_library(libname, _loaderpath)
     55 except OSError:
     56     from pyscf import __path__ as ext_modules

File /mnt/c/MyProgram/anaconda3/envs/pyscfad/lib/python3.9/site-packages/numpy/ctypeslib.py:163, in load_library(libname, loader_path)
    161             raise
    162 ## if no successful return in the libname_ext loop:
--> 163 raise OSError("no file with expected extension")

OSError: no file with expected extension
--------------------------------------------------------------------------------------------------------
Also, I have included the lines:
pyscfad = True
pyscf_numpy_backend = 'jax'
pyscf_scipy_linalg_backend = 'pyscfad'
pyscf_scipy_backend = 'jax'
pyscfad_scf_implicit_diff = True      
pyscfad_ccsd_implicit_diff = True     
in the .pyscf_conf.py both in the home and working directories...

Thanks for helping me,

Yuzhi

**Comment by fishjojo** [comment]
Hi Yuzhi, `pip install` should work for python 3.7. I'll fix the issue with python 3.9.

**Comment by zhouyz08** [comment]
> Hi Yuzhi, the problem you saw when `pip install` is that the cmake does not recognize the -S and -B options. Cmake 3.18 should work. I'll also try to make the installation more robust.

Thanks a lot! I'll try that and close the issue. 
Yuzhi

**Comment by zhouyz08** [comment]
Hi fishjojo, I tried manually compile the pyscf-ad branch and still got the following errors...
'''[  1%] Creating directories for 'libcint'
[  2%] Performing download step (git clone) for 'libcint'
Cloning into 'libcint'...
Switched to a new branch 'ad'
Branch 'ad' set up to track remote branch 'ad' from 'origin'.
[  3%] Performing update step for 'libcint'
HEAD is now at 7c9c765 remove duplicate
[  4%] No patch step for 'libcint'
[  5%] Performing configure step for 'libcint'
**CMake Error: Unknown argument -ldl
CMake Error: Run 'cmake --help' for all supported options.**
CMakeFiles/libcint.dir/build.make:91: recipe for target 'deps/src/libcint-stamp/libcint-configure' failed
make[2]: *** [deps/src/libcint-stamp/libcint-configure] Error 1
CMakeFiles/Makefile2:271: recipe for target 'CMakeFiles/libcint.dir/all' failed
make[1]: *** [CMakeFiles/libcint.dir/all] Error 2
Makefile:90: recipe for target 'all' failed
make: *** [all] Error 2'''

I have just updated my cmake to 3.22.1 inside the conda. By the way, I fully understand this is a brand new project so just leave the message at your convenience.

Best,
Yuzhi

**Comment by fishjojo** [comment]
I can confirm this. But if I try `python setup.py install` at pyscf root, there is no problem. I'll take a look.

**Comment by fishjojo** [comment]
It seems libcint does not work with higher versions of cmake. cmake 3.18 should definitely work. we need to fix the build for other cmake versions.

**Comment by zhouyz08** [comment]
I tried with 3.18 and it works! Thanks a lot for your help!

Best,

Yuzhi
