### ISSUE TITLE
building pyscfadlib with intel mkl

### ISSUE THREAD

**Issue by mkrompiec** [fishjojo/pyscfad#45]
I was struggling to get the build to work with Intel MKL (in pyenv, GCC 11.4). Same error as reported in https://community.intel.com/t5/Intel-oneAPI-Math-Kernel-Library/mkl-fails-to-load/m-p/1155538, and the same fix helped:
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libmkl_def.so:/usr/lib/x86_64-linux-gnu/libmkl_avx2.so:/usr/lib/x86_64-linux-gnu/libmkl_core.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_lp64.so:/usr/lib/x86_64-linux-gnu/libmkl_intel_thread.so:/usr/lib/x86_64-linux-gnu/libiomp5.so
Is it an issue of my environment or could it be something related to "static MKL linkage" as suggested by the Intel engineer in the link above?

**Comment by fishjojo** [comment]
This may be caused by that the environment for MKL is not correctly set.
For example, if MKL is installed through intel oneapi, one could `source /opt/intel/oneapi/setvars.sh`. Otherwise, MKL installed by conda should have the environment set correctly.
