### ISSUE TITLE
Differences in SCF implementation in PySCF and PySCFAD. Bug or different conventions??

### ISSUE THREAD

**Issue by mkrompiec** [fishjojo/pyscfad#46]
Hi, I'm tracing the source of different results obtained in pyscf and pyscfad for the same system. It turns out that the difference is already at the HF level, even thought the HF energies (and also MP2 & CCSD energies) are the same! My test case is N2 molecule with 1.0 A bond length. Is there a difference in conventions between pyscf and pyscfad?

If I run RHF in pyscf and pyscfad, I get the same HF energies but different MO coefficients, different two-electron integrals in MO basis and different Fock operators in MO basis. It is not a matter of different initial guesses, as repeating with `mf_jax.kernel(dm0=mf.make_rdm1())` doesn't change the result. 
If I force the MO coefficients to be the same, the HF energies differ significantly, but ERIs are the same (although diagonals of the Fock matrices differ).

```
from pyscfad import gto, scf, ao2mo
from pyscf import gto as gto_, scf as scf_, ao2mo as ao2mo_
import jax
import jax.numpy as jnp

force_same_mos = True

b = 1.0
mol = gto_.Mole()
mol.verbose = 0
mol.incore_anyway=True
mol.build(atom = [["N", (0., 0., 0.)],["N", (0., 0., b)],], basis = "sto-3g")
mf = scf_.RHF(mol).run()
mol_jax = gto.Mole()
mol_jax.verbose = 0
mol_jax.incore_anyway=True
mol_jax.build(atom = [["N", (0., 0., 0.)],["N", (0., 0., b)],], basis = "sto-3g")
mf_jax = scf.RHF(mol_jax).run()
if force_same_mos:
    mf_jax.mo_coeff = jnp.asarray(mf.mo_coeff)
    mf_jax.max_cycle = 0
    mf_jax.kernel()
jax.debug.print("e_tot equal? {eq}", eq=jnp.isclose(mf.e_tot, mf_jax.e_tot)) 
jax.debug.print("PySCF: {e}", e=mf.e_tot) 
jax.debug.print("PySCFAD: {e}", e=mf_jax.e_tot) 
jax.debug.print("mo_coeff equal? {eq}", eq=jnp.allclose(mf.mo_coeff, mf_jax.mo_coeff)) 
jax.debug.print("mo_coeff diff norm {diff}", diff = jnp.linalg.norm(mf.mo_coeff - mf_jax.mo_coeff))
two_electron_pyscf = ao2mo_.incore.full(mf._eri, mf.mo_coeff, compact=False).reshape([mf.mo_coeff.shape[1]] * 4)
two_electron_pyscfad = ao2mo.incore.full(mf_jax._eri, mf_jax.mo_coeff, compact=False).reshape([mf_jax.mo_coeff.shape[1]] * 4)
jax.debug.print("ERI equal? {eq}", eq = jnp.allclose(two_electron_pyscf,two_electron_pyscfad))
jax.debug.print("ERI diff norm {diff}", diff = jnp.linalg.norm(two_electron_pyscf - two_electron_pyscfad))
fock = mf.mo_coeff.T @ mf.get_fock() @ mf.mo_coeff
fock_diag = fock.diagonal()
fock_jax = mf_jax.mo_coeff.T @ mf_jax.get_fock() @ mf_jax.mo_coeff
fock_diag_jax = fock_jax.diagonal()
jax.debug.print("Fock diagonal equal? {eq}", eq = jnp.allclose(fock_jax,fock_diag_jax))
```

If force_same_mos == True, I get:

```
e_tot equal? False
PySCF: -107.4195324516821
PySCFAD: -108.04529323875562
mo_coeff equal? True
mo_coeff diff norm 0.0
ERI equal? True
ERI diff norm 5.102517976024374e-15
Fock diagonal equal? False
```

If force_same_mos == False, I get:

```
e_tot equal? True
PySCF: -107.4195324516821
PySCFAD: -107.41953245168213
mo_coeff equal? False
mo_coeff diff norm 4.526551531860361
ERI equal? False
ERI diff norm 3.5848316081513745
Fock diagonal equal? False
```
At first, I thought some  MO coefficients have just opposite signs (this is the case if the test is performed on H2 instead of N2), but it's not true in general and can be easily verified by inspecting `jnp.linalg.norm(jnp.abs(mf.mo_coeff) - jnp.abs(mf_jax.mo_coeff))`.

The above was obtained with the dev branch of pyscfad (downloaded on Sept. 3) and pyscf 2.6.2, running on python 3.12.5 on WSL. I can reproduce this on Google Colab with pyscf 2.6.2, pyscfad 0.1.6 and pyscfadlib 0.1.7 (or 0.1.6), on python 3.10.12, see https://colab.research.google.com/drive/1-piOzc911Qay8ECLqclHOJFSy40aB3nh?usp=sharing

Nb. pyscf 0.1.7 doesn't seem to be working correctly with pyscfadlib 0.1.7 (crashed due to lapack)

**Comment by fishjojo** [comment]
This is possibly a design flaw of pyscf (and pyscfad follows the same design).
Setting `mo_coeff` alone does not force SCF to start with the converged density matrix. You will also need to pass `dm0` into the `kernel` function.
You may verify that your script will lead to the same "wrong" result even by replacing the pyscfad part with pyscf.
So the correct way to do this would be
```
if force_same_mos:
    mf_jax.mo_coeff = jnp.asarray(mf.mo_coeff)
    mf_jax.max_cycle = 0
    mf_jax.kernel(dm0=mf.make_rdm1())
```
And the last line should be
```
fock_diag_jax = jnp.diag(fock_jax.diagonal())
```

**Comment by fishjojo** [comment]
Also N2 has degenerate states, so the MO coefficients for these states can differ by a unitary transformation in two calculations. This is also the case in pyscf.

**Comment by mkrompiec** [comment]
Thank you very much! I am getting the correct answer now:
```
e_tot equal? True
PySCF: -107.41953245168216
PySCFAD: -107.4195324516821
mo_coeff equal? True
mo_coeff diff norm 0.0
ERI equal? True
ERI diff norm 4.9784828547863905e-15
Fock diagonal equal? True
```

**Comment by mkrompiec** [comment]
Actually, `fock_diag_jax = jnp.diag(fock_jax.diagonal()) ` would be incorrect, but both `jnp.diag(fock_jax)` and `fock_jax.diagonal()` are fine.
What took me a while to figure out is that this: `mf.kernel(dm0)` is correct both in pyscf and pyscfad, while this: `mf.kernel(dm0=dm0)` doesn't work in pyscfad (i.e. it's equivalent to `mf.kernel()`).

**Comment by fishjojo** [comment]
Sorry, I don't understand. `mf.kernel(dm0=dm0)` should behave the same in pyscfad and pyscf.

**Comment by mkrompiec** [comment]
Well, I was too quick, apologies. It was `mf.run()` and the behaviour is the same in pyscf and pyscfad:
`mf2.run(dm0=mf1.make_rdm1())` doesn't work while `mf2.run(mf1.make_rdm1())` does.

**Comment by fishjojo** [comment]
I see. The `run` function is defined in [pyscf](https://github.com/pyscf/pyscf/blob/3dc4547e518f06223f239ad57cbd21ad3f6f570f/pyscf/lib/misc.py#L630-L639), and its design may not be optimal.
