### ISSUE TITLE
Is B3LYP numpy or libxc?

### ISSUE THREAD

**Issue by alexm-gc** [fishjojo/pyscfad#5]
Absolutely amazing work, it was an absolutely delight to read through your code! 

**My Goal:** Implement b3lyp in jax.numpy 

**Advantages:** I immediately get `jax.grad`, `jax.jit` and I can use any processing unit. 

[This example](https://github.com/fishjojo/pyscfad/blob/bdc60aeb203140d6e7046072ecdde79806b47c6a/examples/dft/00-simple.py#L15) uses "b3lyp". The "b3lyp" functional is used by [get_veff](https://github.com/fishjojo/pyscfad/blob/bdc60aeb203140d6e7046072ecdde79806b47c6a/pyscfad/dft/rks.py#L56) which calls [nr_rks](https://github.com/fishjojo/pyscfad/blob/bdc60aeb203140d6e7046072ecdde79806b47c6a/pyscfad/dft/numint.py#L101) which calls [eval_xc](https://github.com/fishjojo/pyscfad/blob/bdc60aeb203140d6e7046072ecdde79806b47c6a/pyscfad/dft/numint.py#L408) which calls [pyscfad.libxc](https://github.com/fishjojo/pyscfad/blob/bdc60aeb203140d6e7046072ecdde79806b47c6a/pyscfad/dft/libxc.py#L7) which in the end calls the original [pyscf.libxc](https://github.com/fishjojo/pyscfad/blob/bdc60aeb203140d6e7046072ecdde79806b47c6a/pyscfad/dft/libxc.py#L25). 

**Question 0.** This function evaluates b3lyp by calling PySCF. This call is, quite cleverly, decorated with jax.custom_jvp so we can get automatic differentation. However, because the b3lyp evaluation is done by underlying C code, we cannot use `jax.jit` to run on any e.g. GPU/TPU. Is this wrong?

**Question 1.** Have you seen any jax.numpy implementation of b3lyp?

Please do not hesitate to correct any misunderstanding I may have.

**Comment by fishjojo** [comment]
Hi @alexm-gc, thanks for your questions.
0. You are right. Current implementation simply calls libxc to compute all the needed quantities. 
1. No I haven't. I think implementing LDA and GGA functionals using python is not too hard. Though I'm not sure how well jax jit can optimize the code.
