### ISSUE TITLE
takebak_2d and take_2d?

### ISSUE THREAD

**Issue by mkrompiec** [fishjojo/pyscfad#58]
Are jax-friendly versions of pyscf.lib.take_2d and takebak_2d available?

**Comment by fishjojo** [comment]
`take_2d` can be replaced with `a[idx[:,None],idy]`.
But the logic of `takebak_2d` does not work for jax backend, because the argument `out` cannot be updated in-place.

**Comment by fishjojo** [comment]
> Actually, this works and (reportedly) jit can compile it to efficient code:
> 
> ```
> def takebak_2d(out, a, idx, idy):
>     #out[idx[:, None], idy] += a
>     out = out.at[idx[:, None], idy].add(a)
>     return out
> ```

I believe this makes a copy of `out`, doesn't it?

**Comment by mkrompiec** [comment]
Not when they are jitted:
“However, inside a jit()
<https://jax.readthedocs.io/en/latest/_autosummary/jax.jit.html#jax.jit>compiled
function, expressions like x =x.at[idx].set(y) are guaranteed to be applied
in-place.”

https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html

**Comment by fishjojo** [comment]
I tested this, and it seems that the buffer of the input `out` array is not updated.
```
import numpy as np
from jax import jit

@jit
def takebak_2d(out, a, idx, idy):
    out = out.at[idx[:, None], idy].add(a)
    return out

out = np.zeros((4,4))
a = np.ones((2,2))

out1 = takebak_2d(out, a, np.array([1,2]), np.array([2,3]))
print(out)
print(out1)
```

outputs:
```
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 1. 1.]
 [0. 0. 1. 1.]
 [0. 0. 0. 0.]]
```
