### ISSUE TITLE
PyPI wheels appear to be broken

### ISSUE THREAD

**Issue by obackhouse** [fishjojo/pyscfad#60]
The PyPI wheels don't contain most of the source code -- seems to be just whatever `pyscfad/__init__.py` imports. It doesn't look like the `MANFIEST.in` is discovering the files?

**Comment by fishjojo** [comment]
Which wheel specifically?

**Comment by obackhouse** [comment]
My bad, I was mistaken -- I was doing it in a CI runner so it was ambiguous. The issue is actually that 
```
>>> from pyscfad import ao2mo
```
works fine, but
```
>>> import pyscfad
>>> pyscfad.ao2mo
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'pyscfad' has no attribute 'ao2mo'
```
does not. I'll close this since it's a different issue and may be intended anyway.

**Comment by fishjojo** [comment]
No worries. Currently, only a few essential subpackages are exported to the `pyscfad` namespace. Others are not included as there may be circular imports.
