### ISSUE TITLE
Manually compile the ad branch of pyscf

### ISSUE THREAD

**Issue by zhouyz08** [fishjojo/pyscfad#7]
Hi,

I was trying to manually compile the ad branch of pyscf without network. I follow the instructions on pyscf.org and have successfully compiled the libcint, xcfun and libxc. However when compiling the pyscf (ad branch), it throws such error to me:

[ 17%] Building C object gto/CMakeFiles/cgto.dir/ft_ao.c.o
/mnt/c/js/wang/manad/pyscf/pyscf/lib/gto/ft_ao.c: In function ‘GTO_aopair_lazy_contract’:
**/mnt/c/js/wang/manad/pyscf/pyscf/lib/gto/ft_ao.c:1011:26: error: assignment to expression with array type
                 envs->aj = aj[jp];**
                          ^
/mnt/c/js/wang/manad/pyscf/pyscf/lib/gto/ft_ao.c:1019:34: error: assignment to expression with array type
                         envs->ai = ai[ip];
                                  ^
gto/CMakeFiles/cgto.dir/build.make:146: recipe for target 'gto/CMakeFiles/cgto.dir/ft_ao.c.o' failed
make[2]: *** [gto/CMakeFiles/cgto.dir/ft_ao.c.o] Error 1
CMakeFiles/Makefile2:334: recipe for target 'gto/CMakeFiles/cgto.dir/all' failed
make[1]: *** [gto/CMakeFiles/cgto.dir/all] Error 2
Makefile:102: recipe for target 'all' failed
make: *** [all] Error 2

The other thing is, if I switch back to the original branch, I can successfully build the pyscf without this error.

my gcc is 7.5.0 and cmake is 3.18.2.

Any suggestions and thoughts are welcome.

Thanks!

Yuzhi

**Comment by fishjojo** [comment]
The `libcint` library is different. If you clone the `ad` branch of `pyscf` and run the following
```
git clone https://github.com/fishjojo/pyscf.git
cd pyscf
git checkout ad 
cd pyscf/lib
mkdir build 
cd build; cmake ..; make
```
the compilation should work.
Otherwise, you need to use the `ad` branch of https://github.com/fishjojo/libcint.git
I will find some time to make these synced with the current pyscf main branch.

**Comment by zhouyz08** [comment]
> The `libcint` library is different. If you clone the `ad` branch of `pyscf` and run the following
> 
> ```
> git clone https://github.com/fishjojo/pyscf.git
> cd pyscf
> git checkout ad 
> cd pyscf/lib
> mkdir build 
> cd build; cmake ..; make
> ```
> 
> the compilation should work. Otherwise, you need to use the `ad` branch of https://github.com/fishjojo/libcint.git I will find some time to make these synced with the current pyscf main branch.

Thanks! That should work!

Best,
Yuzhi
