### ISSUE TITLE
Implement ROHF in pyscfad

### ISSUE THREAD

**Issue by deyanmihaylov** [fishjojo/pyscfad#9]
Feature request:

I was trying to use the different classes of `scf` and found out that only `RHF` and `UHF` are implemented in `pyscfad`. Since I wanted to use the automatic differentiation of `pyscfad` with `ROHF`, I was wondering if it would be possible to be implemented here too.

**Comment by fishjojo** [comment]
Yes, I can add it.

**Comment by deyanmihaylov** [comment]
That is great to hear. My collaborator Nike Dattani (whom I cannot tag here for some reason) and I will be delighted to use that functionality.

**Comment by ndattani** [comment]
@fishjojo  we optimized the first 4 primitive exponents for the Li atom using UHF, and got:
```
E = -7.376925908376867

S-exponents:                         
3.4866918473739560e+01
5.1775711256586652e+00
1.0515665488904080e+00
4.7758303467345234e-02
```
This is lower than the published energy of -7.3769059.

We managed to get exactly the same energy as the published one, when we optimized the exponents using ROHF. Unfortunately we didn't have access to the derivative of the ROHF energy with respect to exponents, so we had to use a derivate-free optimization method, which requires far more iterations than most methods that use derivatives.

Also, is it possible to get the Hessian of the SCF energy with respect to exponents? This would allow us to speed-up the Newton-Raphson optimization of the exponents.

**Comment by fishjojo** [comment]
@ndattani the Hessian will need a little more work to implement, but I can take a look. ROHF will be ready to use soon.

**Comment by ndattani** [comment]
Beautiful! The Hessian should improve our optimizations!

**Comment by fishjojo** [comment]
Hi, @ndattani @vandan-revanur 
This function is defined here in `pyscf` in the `ad` branch: https://github.com/fishjojo/pyscf/blob/4c3dcfb1226690a9013a0bdaffe08ef9113a3c77/pyscf/lib/misc.py#L1183-L1191
Please check if your `pyscf` is up to date.
The two versions of the `stop_grad` should both work, so you can use either one.
We are in the middle of transferring code from `pyscfad` to `pyscf`, so there may be some inconsistency.
